/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nvqattestation;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SD2023
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public ResultSet rs;
    public PreparedStatement pst;
    DBConnection database = new DBConnection();
    public String CurrentID;
    public AddStudent() {
        database.dbConnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAddStudentClose = new javax.swing.JButton();
        txtMobile = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JFormattedTextField();
        txtNic = new javax.swing.JFormattedTextField();
        btnDelete1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("ADD STUDENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel2.setText("F I L L   I N   T H E   B L A N K S   F O R    R E G I S T R A T I O N   S T U D E N T");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel3.setText("NIC Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setText("Student Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setText("Mobile");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "Mobile"
            }
        ));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 510, 320));

        btnDelete.setBackground(new java.awt.Color(220, 53, 69));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 120, 30));

        btnAdd.setBackground(new java.awt.Color(0, 204, 102));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 120, 30));

        btnUpdate.setBackground(new java.awt.Color(13, 110, 253));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 120, 30));

        btnAddStudentClose.setBackground(new java.awt.Color(255, 84, 84));
        btnAddStudentClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nvqattestation/close.png"))); // NOI18N
        btnAddStudentClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudentClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 30));

        try {
            txtMobile.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileKeyReleased(evt);
            }
        });
        jPanel1.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, 30));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, 30));

        try {
            txtNic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });
        jPanel1.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, 30));

        btnDelete1.setBackground(new java.awt.Color(13, 202, 240));
        btnDelete1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("CLEAR");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nvqattestation/ETI+Website+Graphics.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 1170, 860));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       if(studentTable.getSelectedRow() >= 0){
           try {
               String nic = txtNic.getText();
               String checkisCertificate="SELECT * FROM `student_certificate` WHERE `nic`=?";
               pst=database.con.prepareStatement(checkisCertificate);
               pst.setString(1,nic);
               
               rs = pst.executeQuery();
               
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "Student Already have Certificate !","ERROR !",JOptionPane.ERROR_MESSAGE);
                   clearText();
               }else{
                int confirmAlert = JOptionPane.showConfirmDialog(null, "Do you want to proceed?", "Select an Option...",
				JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
		
                // 0=yes, 1=no, 2=cancel
        
                    if(confirmAlert == 0){
                        String DeleteQuery="DELETE FROM `students` WHERE `nic`=?";
                        pst=database.con.prepareStatement(DeleteQuery);
                        pst.setString(1,CurrentID);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Delete Succesfull");
                        clearText();

                        DefaultTableModel tableModel = (DefaultTableModel) studentTable.getModel();
                        int rowNumber = studentTable.getSelectedRow();
                        tableModel.removeRow(rowNumber); 

                        btnAdd.setEnabled(true);
                    }
               }
               
               
           } catch (SQLException ex) {
               Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        insertData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String nic = txtNic.getText();
        String name = txtName.getText();
        String mobile = txtMobile.getText();
        
        Student student = new Student(nic, name, mobile);
        
        if(studentTable.getSelectedRow() >= 0){
           try {
               String updateQuery = "UPDATE `students` SET `nic`=?,`name`=?,`mobile`=? WHERE `nic`=?";
               pst = database.con.prepareStatement(updateQuery);
               pst.setString(1, student.getNic());
               pst.setString(2, student.getName());
               pst.setString(3, student.getMobile());
               pst.setString(4,CurrentID);
               
               pst.executeUpdate();
               JOptionPane.showMessageDialog(null,"Update Sucessfully");
               
               btnAdd.setEnabled(false);
                             
                updateTable();
               
                txtNic.requestFocus();
                btnAdd.setEnabled(true);
                txtNic.setEditable(true);
                txtName.setEditable(true);
               clearText();
           } catch (SQLException ex) {
               Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddStudentCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentCloseActionPerformed
        this.dispose();
        NvtiUI frame = new NvtiUI();
        frame.setVisible(true);
    }//GEN-LAST:event_btnAddStudentCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        updateTable();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtNic.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        TableModel model = studentTable.getModel();
        int rowNumber = studentTable.getSelectedRow();
        
        txtNic.setText(model.getValueAt(rowNumber, 0).toString());
        txtName.setText(model.getValueAt(rowNumber, 1).toString());
        txtMobile.setText(model.getValueAt(rowNumber, 2).toString());
        
        CurrentID = txtNic.getText();
        
        btnAdd.setEnabled(false);
        txtNic.setEditable(false);
        txtName.setEditable(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        
    }//GEN-LAST:event_studentTableMouseClicked

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        int position = txtNic.getCaretPosition();
        txtNic.setText(txtNic.getText().toUpperCase());
        txtNic.setCaretPosition(position);
    }//GEN-LAST:event_txtNicKeyReleased

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
       clearText();
       btnAdd.setEnabled(true);
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void txtNicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyPressed
       if(evt.getKeyChar()==KeyEvent.VK_ENTER){
           txtName.requestFocus();
       }
    }//GEN-LAST:event_txtNicKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
       if(evt.getKeyChar()==KeyEvent.VK_ENTER){
           txtMobile.requestFocus();
       }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            if(txtMobile.getValue() != null){
                insertData();
                txtNic.requestFocus();
                txtMobile.setValue(null);
            }
          
       }
    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyReleased

    }//GEN-LAST:event_txtMobileKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }
    
    void clearText(){
        txtNic.setText("");
        txtName.setText("");
        txtMobile.setText("");
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);
        txtNic.setEditable(true);
        txtName.setEditable(true);
        txtNic.requestFocus();
    }
    
    boolean validation(){
        try {
            if(txtNic.getText().isEmpty() || txtName.getText().isEmpty() || txtMobile.getValue() == null){
                txtNic.requestFocus();
                JOptionPane.showMessageDialog(null, "All Fields Are Required");
                return false;
            }
//            if(txtNic.getText().length() != 8 || txtNic.getText().length() != 12){
//                txtNic.requestFocus();
//                JOptionPane.showMessageDialog(null, "Invalid NIC");
//                return false;
//            }
            
            String CheckId = "SELECT * FROM `students` WHERE `nic`=?";
            pst = database.con.prepareStatement(CheckId);
            pst.setString(1,txtNic.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID already exists !");
                txtNic.requestFocus();
                return false;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
    
    void updateTable(){
        try {
            DefaultTableModel studentmodel = (DefaultTableModel) studentTable.getModel();
            String getDataQuery = "SELECT * FROM `students`";
            studentmodel.setRowCount(0);
            pst = database.con.prepareStatement(getDataQuery);
            rs = pst.executeQuery();
            while(rs.next()){
                String nic = rs.getString(1);
                String name = rs.getString(2);
                String mobile = rs.getString(3);
                
                String[] data = {nic,name,mobile};
                studentmodel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void insertData(){
        String insertQuery = "INSERT INTO `students`(`nic`, `name`, `mobile`) VALUES (?,?,?)";
        
        String nic = txtNic.getText();
        String name = txtName.getText();
        String mobile = txtMobile.getText();
        
        Student student = new Student(nic, name, mobile);
        
        try {
            if(validation()){
                pst = database.con.prepareStatement(insertQuery);
                pst.setString(1,student.getNic());
                pst.setString(2,student.getName());
                pst.setString(3,student.getMobile());
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Student added Succefully !");
                
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);
                                
                updateTable();
                
                clearText();
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddStudentClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentTable;
    private javax.swing.JFormattedTextField txtMobile;
    private javax.swing.JFormattedTextField txtName;
    private javax.swing.JFormattedTextField txtNic;
    // End of variables declaration//GEN-END:variables
}
