/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nvqattestation;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SD2023
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public ResultSet rs;
    public PreparedStatement pst;
    DBConnection database = new DBConnection();
    public Register() {
        database.dbConnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRegName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegPassword = new javax.swing.JPasswordField();
        txtRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRegRePassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("NVQ ATTESTATION SYSTEM REGISTER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));
        jPanel1.add(txtRegName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, -1));
        jPanel1.add(txtRegUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 350, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 170, -1));
        jPanel1.add(txtRegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 350, 30));

        txtRegister.setBackground(new java.awt.Color(13, 110, 253));
        txtRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtRegister.setText("Register");
        txtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(txtRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Re-Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, -1));
        jPanel1.add(txtRegRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 350, 30));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nvqattestation/register.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nvqattestation/68-682087_about-web-bay-technology-background-in-png.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1001, 521));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        UserLogin frame = new UserLogin();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterActionPerformed
        String insertUser = "INSERT INTO `user`(`name`, `username`, `password`) VALUES (?,?,?)";
        
        String name = txtRegUserName.getText();
        String username = txtRegUserName.getText();
        String passowrd = txtRegPassword.getText();
        
        User user = new User(name, username, passowrd);
        if(validation()){
            try {
                pst = database.con.prepareStatement(insertUser);
                pst.setString(1,user.getName());
                pst.setString(2,user.getUsername());
                pst.setString(3,user.getPassword());
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "User Registration Succefully !");
                
                clearFields();
                
                this.dispose();
                UserLogin frame = new UserLogin();
                frame.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_txtRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
    void clearFields(){
        txtRegName.setText("");
        txtRegUserName.setText("");
        txtRegPassword.setText("");
        txtRegRePassword.setText("");
    }
    
    boolean validation(){
        
            if(txtRegName.getText().isEmpty() || txtRegUserName.getText().isEmpty() || txtRegPassword.getText().isEmpty() || txtRegRePassword.getText().isEmpty()){
                txtRegName.requestFocus();
                JOptionPane.showMessageDialog(null, "All Fields Are Required");
                return false;
            }
            
            if(txtRegPassword.getText().length() < 6){
                txtRegPassword.requestFocus();
                JOptionPane.showMessageDialog(null, "Password Will be minimum 6 characters !","DELETE",JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
//            String password = new String(txtRegPassword.getPassword());
//            String repassword = new String(txtRegPassword.getPassword());
//            if(password !=repassword){
//                txtRegPassword.setText("");
//                txtRegRePassword.setText("");
//                txtRegPassword.requestFocus();
//                JOptionPane.showMessageDialog(null, "Password and Re-Password not matched !","DELETE",JOptionPane.WARNING_MESSAGE);
//                return false;
//            }
            
            if(txtRegUserName.getText().length() < 2){
                txtRegUserName.requestFocus();
                JOptionPane.showMessageDialog(null, "Invalid UserName Please use minimum 2 or more characters !","DELETE",JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
        try {
            String checkUsername="SELECT  `username` FROM `user` WHERE `username`=?";
            pst = database.con.prepareStatement(checkUsername);
            pst.setString(1,txtRegUserName.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"This UserName is Already used !");
                txtRegUserName.requestFocus();
                return false;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRegName;
    private javax.swing.JPasswordField txtRegPassword;
    private javax.swing.JPasswordField txtRegRePassword;
    private javax.swing.JTextField txtRegUserName;
    private javax.swing.JButton txtRegister;
    // End of variables declaration//GEN-END:variables
}
